In [1]:
import numpy as np

In [5]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
arr[5:10]

array([5, 6, 7, 8, 9])

In [15]:
arr1 = list(range(1,11))
arr1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [14]:
arr1[:4]

[0, 1, 2, 3]

In [25]:
arr_2nd = np.arange(50).reshape(5,10)

In [26]:
arr_2nd

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [30]:
arr_2nd[1,:2]


array([10, 11])