In [1]:
import numpy as np
import pandas as pd

In [5]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
arr[5:10]

array([5, 6, 7, 8, 9])

In [15]:
arr1 = list(range(1,11))
arr1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [14]:
arr1[:4]

[0, 1, 2, 3]

In [25]:
arr_2nd = np.arange(50).reshape(5,10)

In [26]:
arr_2nd

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [30]:
arr_2nd[1,:2]


array([10, 11])

In [2]:
from numpy.random import randn

In [3]:
np.random.seed(100)

In [4]:
df = pd.DataFrame(randn(5,4),[1,2,3,4,5],['a','b','c','d'])

In [5]:
df

a         b         c         d
1 -1.749765  0.342680  1.153036 -0.252436
2  0.981321  0.514219  0.221180 -1.070043
3 -0.189496  0.255001 -0.458027  0.435163
4 -0.583595  0.816847  0.672721 -0.104411
5 -0.531280  1.029733 -0.438136 -1.118318

In [9]:
df.drop(1, inplace=True)

In [13]:
df

a         b         c         d
2  0.981321  0.514219  0.221180 -1.070043
3 -0.189496  0.255001 -0.458027  0.435163
4 -0.583595  0.816847  0.672721 -0.104411
5 -0.531280  1.029733 -0.438136 -1.118318

In [15]:
df[df['a']<0][['c','d']]

c         d
3 -0.458027  0.435163
4  0.672721 -0.104411
5 -0.438136 -1.118318